[workspace]
members = [
    "fastborsh",
    "fastborsh-core",
    "fastborsh-derive",
]
resolver = "3"

[workspace.package]
name = "fastborsh"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
borsh = { version = "1.5.5", default-features = false, features = ["std"] }
