[package]
name = "fastborsh-derive"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
quote = "1.0"
syn = { version = "2.0", default-features = true }

[lib]
proc-macro = true
