[package]
name = "fastborsh-derive"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[lib]
proc-macro = true
